# Generated by Django 5.2.4 on 2026-06-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('eyebrow', models.CharField(blank=True, help_text="Small text above title e.g. 'New Arrivals 2026'", max_length=100)),
                ('title', models.CharField(blank=True, help_text="Use \\n for line break e.g. 'The New\\nFashion Collection'", max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('btn1_text', models.CharField(blank=True, help_text="First button text e.g. 'Shop Now'", max_length=50)),
                ('btn1_url', models.CharField(blank=True, default='/product-list/', max_length=200)),
                ('btn2_text', models.CharField(blank=True, help_text="Second button text e.g. 'Women's Edit'", max_length=50)),
                ('btn2_url', models.CharField(blank=True, default='/product-list/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number shows first')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
